version: '3.7'
services:
  bot:
    container_name: hawk
    image: theprogrammershangout/hawk:latest
    volumes:
      - type: bind
        source: ./config/config.json
        target: /config/config.json
    restart: always
    env_file:
      - .env

volumes:
  app:
