version: '3.7'
services:
  starter:
    container_name: Hawk
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./data/configuration.json
        target: /data/configuration.json
    restart: always
    env_file:
      - .env

volumes:
  app: