version: '3.7'
services:
  bot:
    container_name: hawk
    image: theprogrammershangout/hawk:latest
    volumes:
      - type: bind
        source: ./data/config.json
        target: /data/config.json
    restart: unless-stopped
    env_file:
      - .env

volumes:
  app:
