name: Docker

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          username: ${{ secrets. DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: theprogrammershangout/hawk
          tags: latest